### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by dazinator** [vitaliy-leschenko/traefik-forwardauth-azuread#1]
I was thinking of using this at work.
Would it be possible to add a licence to this repo so we now where things stand in terms of being able to use?

**Comment by vitaliy-leschenko** [comment]
Please feel free to use it as you want.

**Comment by vitaliy-leschenko** [comment]
I think Apache v2 will be OK for the project. The license file has been added.

**Comment by dazinator** [comment]
Many thanks!
